# Site settings
name: Internet of Things
title: Internet of Things
description: > # this means to ignore newlines until "baseurl:"
  Progetti del corso Internet of Things dell'Università del Salento nel 2025.
baseurl: "" # the subpath of your site, e.g. /blog
paginate: 10

# Build settings
markdown: kramdown
